#!/bin/bash
opwd=`pwd`; APACHI_HOME=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd ); cd $opwd
PATH=$PATH:$APACHI_HOME/bin;

export APACHI_HOME PATH
echo "
	Thank you for installing APAchi tools
	Please copy and paste the following in ~/.bash_profile

	## copy from here
	APACHI_HOME='"$APACHI_HOME"' 
	PATH=\$APACHI_HOME/bin:\$PATH
	export APACHI_HOME PATH
	## to here

	and then type 
	$source ~/.bash_profile

	for usage please visit 
	https://github.com/hmgene/APAchi/wiki

"


#elif [ $# -eq  1 ];then
#	if [ $1 = "install" ];then
#echo '	## added by hmtools
#	HMHOME=$HMHOME; export HMHOME;
#	PATH=$PATH:$HMHOME/bin; export PATH
#	## end
# ' >> ~/.bash_profile
#	source ~/.bash_profile
#	else
#		. "$HMHOME/src/${1}.sh"
#		compgen -A function | grep "^$1\+" | grep -vE "^dequote|^quote|^in_array"
#	fi
#else 
#	. "$HMHOME/src/$1.sh";
#	$1.$2 ${@:3}
#fi
